"""empty message

Revision ID: 2bb9e5f3829b
Revises: 5a5398ff00b4
Create Date: 2024-11-02 13:45:23.378905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb9e5f3829b'
down_revision = '5a5398ff00b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('specification')

    # ### end Alembic commands ###
